### ISSUE TITLE
Error Loading Extension 

### ISSUE THREAD

**Issue by Kamalpaneru** [adamisntdead/NoGithubDarkMode#2]
When trying to load this extension,the chrome gives out the following error message

Failed to load extension from: ~/Downloads/NoGithubDarkMode-master
Default locale was specified, but _locales subtree is missing.

**Comment by m-sureshraj** [comment]
The reason for this error:

If we specified **"default_locale": "en"** property in manifest.json file, chrome will looking for a file called **messages.json** inside **_locales/en** dir, in this case extension does not have a dir called _locales, so chrome will throw error.

![i18n-hierarchy](https://cloud.githubusercontent.com/assets/12813750/22861199/e90c69c0-f138-11e6-92bf-114aa88690d0.gif)

@Kamalpaneru To fix this issue you can manually delete **"default_locale": "en"** property from **manifest.json** file.

@adamisntdead [internationalization support](https://developer.chrome.com/extensions/i18n)

**Comment by adamisntdead** [comment]
I will fix this now, thanks for the heads up!

**Comment by adamisntdead** [comment]
Fixed in version 0.0.2, See the commit [5450d08](https://github.com/adamisntdead/NoGithubDarkMode/commit/5450d08b052c47fa56a2d1a114ad187f3e46a587). 

##### Thanks for letting me know, @Kamalpaneru, and thanks for the help @m-sureshraj! 👍
