### ISSUE TITLE
Github style has changed

### ISSUE THREAD

**Issue by twixr** [adamisntdead/NoGithubDarkMode#3]
Github just changes their styling on the header.
Instead of the class `header header-dark` it is now just `header` with a `color` and `background-color` property.

It's easily changed, but I don't know the right color for the old header.

**Comment by twixr** [comment]
I've created a start..
This changes the color of the background, the logo, the notification icon (the blue dot) and the search-scope ("This repository")

Todo: The search bar

```
document.querySelector('.header').style.backgroundColor = "#f5f5f5";
document.querySelector('.header-logo-invertocat').style.color = "#555";
document.querySelector('.header-search-scope').style.color = "#555";
document.querySelector('.notification-indicator .mail-status').style.border = "none";
var headerLinks = document.querySelectorAll(".header-nav-link");
for (var i = 0; i < headerLinks.length; i++) {
  headerLinks[i].style.color = "#555";
}
```

The color for the light background: ```#f5f5f5```
The color for the dark text: ```#555```

I've got the old style classes in a gist:
https://gist.github.com/jessereitsma/7f405b84299b490020d53188c34b1f03

**Comment by adamisntdead** [comment]
Works here now!

See version 0.0.3
